/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2026-02-02 17:39:36
*/
/* FAULT METADATA: '{"sin":"sin","internalCount":4,"boundaryCount":4,"sout":"sout","order":[{"width":1,"kind":"dff","name":"_12_","ordinal":0},{"width":1,"kind":"dff","name":"_13_","ordinal":0},{"width":1,"kind":"dff","name":"_14_","ordinal":0},{"width":1,"kind":"dff","name":"_15_","ordinal":0},{"width":4,"kind":"output","name":"q","ordinal":0}],"shift":"shift"}' END FAULT METADATA */
/* Generated by Yosys 0.12+45 (git sha1 UNKNOWN, gcc 8.3.1 -fPIC -Os) */

module counter_4bit(clk, reset, q, sin, shift, sout, tck, test);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire \__BoundaryScanRegister_output__0__.din ;
  wire \__BoundaryScanRegister_output__0__.sin ;
  wire \__BoundaryScanRegister_output__0__.sout ;
  wire \__BoundaryScanRegister_output__1__.din ;
  wire \__BoundaryScanRegister_output__1__.sout ;
  wire \__BoundaryScanRegister_output__2__.din ;
  wire \__BoundaryScanRegister_output__2__.sout ;
  wire \__uuf__._04_ ;
  wire \__uuf__.__clk_source__ ;
  input clk;
  output [3:0] q;
  input reset;
  input shift;
  input sin;
  output sout;
  input tck;
  input test;
  INVX1 _29_ (
    .A(reset),
    .Y(_00_)
  );
  INVX1 _30_ (
    .A(\__BoundaryScanRegister_output__0__.sin ),
    .Y(_12_)
  );
  INVX1 _31_ (
    .A(\__BoundaryScanRegister_output__0__.sout ),
    .Y(_13_)
  );
  INVX1 _32_ (
    .A(\__BoundaryScanRegister_output__2__.din ),
    .Y(_14_)
  );
  INVX1 _33_ (
    .A(clk),
    .Y(_15_)
  );
  MUX2X1 _34_ (
    .A(\__BoundaryScanRegister_output__0__.sin ),
    .B(\__BoundaryScanRegister_output__0__.din ),
    .S(shift),
    .Y(_16_)
  );
  INVX1 _35_ (
    .A(_16_),
    .Y(_04_)
  );
  NOR2X1 _36_ (
    .A(shift),
    .B(\__BoundaryScanRegister_output__1__.din ),
    .Y(_17_)
  );
  AOI21X1 _37_ (
    .A(shift),
    .B(_13_),
    .C(_17_),
    .Y(_05_)
  );
  NOR2X1 _38_ (
    .A(shift),
    .B(_14_),
    .Y(_18_)
  );
  NAND2X1 _39_ (
    .A(shift),
    .B(\__BoundaryScanRegister_output__1__.sout ),
    .Y(_19_)
  );
  OAI21X1 _40_ (
    .A(shift),
    .B(_14_),
    .C(_19_),
    .Y(_06_)
  );
  NOR2X1 _41_ (
    .A(_12_),
    .B(shift),
    .Y(_20_)
  );
  NAND2X1 _42_ (
    .A(shift),
    .B(\__BoundaryScanRegister_output__2__.sout ),
    .Y(_21_)
  );
  OAI21X1 _43_ (
    .A(_12_),
    .B(shift),
    .C(_21_),
    .Y(_07_)
  );
  NAND2X1 _44_ (
    .A(shift),
    .B(sin),
    .Y(_22_)
  );
  OAI21X1 _45_ (
    .A(\__BoundaryScanRegister_output__0__.din ),
    .B(shift),
    .C(_22_),
    .Y(_08_)
  );
  NAND2X1 _46_ (
    .A(\__BoundaryScanRegister_output__0__.din ),
    .B(shift),
    .Y(_23_)
  );
  OAI21X1 _47_ (
    .A(\__BoundaryScanRegister_output__0__.din ),
    .B(shift),
    .C(\__BoundaryScanRegister_output__1__.din ),
    .Y(_24_)
  );
  OAI21X1 _48_ (
    .A(\__BoundaryScanRegister_output__0__.din ),
    .B(\__BoundaryScanRegister_output__1__.din ),
    .C(_24_),
    .Y(_25_)
  );
  NAND2X1 _49_ (
    .A(_23_),
    .B(_25_),
    .Y(_09_)
  );
  XNOR2X1 _50_ (
    .A(_18_),
    .B(_24_),
    .Y(_10_)
  );
  OAI21X1 _51_ (
    .A(\__BoundaryScanRegister_output__0__.din ),
    .B(shift),
    .C(\__BoundaryScanRegister_output__2__.din ),
    .Y(_26_)
  );
  NOR2X1 _52_ (
    .A(_17_),
    .B(_26_),
    .Y(_27_)
  );
  XOR2X1 _53_ (
    .A(_20_),
    .B(_27_),
    .Y(_11_)
  );
  NAND2X1 _54_ (
    .A(tck),
    .B(test),
    .Y(_28_)
  );
  OAI21X1 _55_ (
    .A(_15_),
    .B(test),
    .C(_28_),
    .Y(\__uuf__.__clk_source__ )
  );
  INVX1 _56_ (
    .A(reset),
    .Y(_01_)
  );
  INVX1 _57_ (
    .A(reset),
    .Y(_02_)
  );
  INVX1 _58_ (
    .A(reset),
    .Y(_03_)
  );
  INVX1 _59_ (
    .A(reset),
    .Y(\__uuf__._04_ )
  );
  DFFSR _60_ (
    .CLK(tck),
    .D(_04_),
    .Q(\__BoundaryScanRegister_output__0__.sout ),
    .R(_00_),
    .S(1'h1)
  );
  DFFSR _61_ (
    .CLK(tck),
    .D(_05_),
    .Q(\__BoundaryScanRegister_output__1__.sout ),
    .R(_01_),
    .S(1'h1)
  );
  DFFSR _62_ (
    .CLK(tck),
    .D(_06_),
    .Q(\__BoundaryScanRegister_output__2__.sout ),
    .R(_02_),
    .S(1'h1)
  );
  DFFSR _63_ (
    .CLK(tck),
    .D(_07_),
    .Q(sout),
    .R(_03_),
    .S(1'h1)
  );
  DFFSR \__uuf__._12_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_08_),
    .Q(\__BoundaryScanRegister_output__0__.din ),
    .R(\__uuf__._04_ ),
    .S(1'h1)
  );
  DFFSR \__uuf__._13_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_09_),
    .Q(\__BoundaryScanRegister_output__1__.din ),
    .R(\__uuf__._04_ ),
    .S(1'h1)
  );
  DFFSR \__uuf__._14_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_10_),
    .Q(\__BoundaryScanRegister_output__2__.din ),
    .R(\__uuf__._04_ ),
    .S(1'h1)
  );
  DFFSR \__uuf__._15_  (
    .CLK(\__uuf__.__clk_source__ ),
    .D(_11_),
    .Q(\__BoundaryScanRegister_output__0__.sin ),
    .R(\__uuf__._04_ ),
    .S(1'h1)
  );
  assign q = { \__BoundaryScanRegister_output__0__.sin , \__BoundaryScanRegister_output__2__.din , \__BoundaryScanRegister_output__1__.din , \__BoundaryScanRegister_output__0__.din  };
endmodule

