/* Generated by Yosys 0.60+70 (git sha1 8101c87fa, clang++ 18.1.8 -fPIC -O3) */

(* top =  1  *)
(* src = "counter_4bit.v:1.1-14.10" *)
module counter_4bit(clk, reset, q);
  (* src = "counter_4bit.v:2.9-2.12" *)
  input clk;
  wire clk;
  (* src = "counter_4bit.v:3.9-3.14" *)
  input reset;
  wire reset;
  (* src = "counter_4bit.v:4.20-4.21" *)
  output [3:0] q;
  wire [3:0] q;
  wire _00_;
  wire _01_;
  (* force_downto = 32'd1 *)
  (* src = "counter_4bit.v:11.10-11.15|/home/niranjan/tools/oss-cad-suite/lib/../share/yosys/techmap.v:287.21-287.22" *)
  wire [3:0] _02_;
  (* force_downto = 32'd1 *)
  (* src = "counter_4bit.v:11.10-11.15|/home/niranjan/tools/oss-cad-suite/lib/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _03_;
  wire _04_;
  assign _02_[0] = ~q[0];
  assign _03_[1] = q[1] ^ q[0];
  assign _00_ = ~(q[1] & q[0]);
  assign _03_[2] = ~(_00_ ^ q[2]);
  assign _01_ = q[2] & ~(_00_);
  assign _03_[3] = _01_ ^ q[3];
  assign _04_ = ~reset;
  (* src = "counter_4bit.v:7.1-12.4" *)
  DFFSR _12_ (
    .CLK(clk),
    .D(_02_[0]),
    .Q(q[0]),
    .R(_04_),
    .S(1'h1)
  );
  (* src = "counter_4bit.v:7.1-12.4" *)
  DFFSR _13_ (
    .CLK(clk),
    .D(_03_[1]),
    .Q(q[1]),
    .R(_04_),
    .S(1'h1)
  );
  (* src = "counter_4bit.v:7.1-12.4" *)
  DFFSR _14_ (
    .CLK(clk),
    .D(_03_[2]),
    .Q(q[2]),
    .R(_04_),
    .S(1'h1)
  );
  (* src = "counter_4bit.v:7.1-12.4" *)
  DFFSR _15_ (
    .CLK(clk),
    .D(_03_[3]),
    .Q(q[3]),
    .R(_04_),
    .S(1'h1)
  );
  assign _02_[3:1] = q[3:1];
  assign _03_[0] = _02_[0];
endmodule
